version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_ORIGINS=http://localhost:3001
      - DEVICE=cuda
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/results:/app/backend/results
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
